---
title: "Lab 6: A Matter of Taste"
---

Be sure to tag your group mates when you submit this to Gradescope!

#### Question 1

List any changes that you made to your experimental protocol from when you formulated it on Wednesday and when you executed it Friday.


#### Question 2

Create a data frame based of the data you collected and print it out into your lab report. You can print all rows your data frame using `print(my_df, n = nrow(my_df))`. Consult the notes "A Tool for Computing with Data" for a refresher of how to make a data frame.

Does the data frame differ at all from the one that you sketched into your experimental protocol? If so, how?


#### Question 3

Create a visualization of the data you collected (not the null distribution) similar to the one you sketched in the handout. Does it look clearly in support of your claim or contrary to your claim or somewhere in between?


#### Question 4

Conduct a hypothesis test to determine whether your data is consistent with the null hypothesis. Be sure to provide.

a. The null and alternative hypotheses.

b. The value of the observed test statistic.

c. A visualization of the null distribution and observed test statistic with the p-value shaded in.

d. The p-value and your conclusion (use $\alpha = .05$) regarding null hypothesis and original claim.
    
    
#### Question 5

A thought experiment: if you did not find a significant effect, speculate as to what you could change about your protocol to increase the chance that you find an effect. If you did find a significant effect, speculate as to what you would change about your protocol if you wanted to decrease the chance that you'd find an effect if you were to repeat the experiment.